package pe.ayni.booking;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.math.BigDecimal;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.test.context.event.ApplicationEvents;
import org.springframework.test.context.event.RecordApplicationEvents;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.ResultActions;
import org.testcontainers.containers.PostgreSQLContainer;
import pe.ayni.booking.BookingTestConfig.FailingConfirmation;
import pe.ayni.booking.domain.model.HourBlock;
import pe.ayni.booking.infrastructure.HourBlockRepository;
import pe.ayni.identity.IdentityApi;
import pe.ayni.identity.TenantView;
import pe.ayni.shared.domain.CreditType;
import pe.ayni.shared.domain.Credits;
import pe.ayni.shared.tenancy.TenantContext;
import pe.ayni.skills.CatalogItemView;
import pe.ayni.skills.CatalogScope;
import pe.ayni.skills.SkillsApi;
import pe.ayni.wallet.WalletApi;

/**
 * The world every US03 scenario starts from, against a real PostgreSQL: a tutor of UPC who is free
 * tomorrow from nine to twelve, Lima time, and two students, Ana and Bruno.
 *
 * <p>The tutor's hours are real: they are generated by declaring the availability over HTTP, the
 * way US19 does it. identity and skills are the seams, mocked with the answers the real modules
 * give. Wallet, sessions and everything inside booking are the real thing.
 *
 * <p>Every scenario class extends this one, so they all share one application context: the same
 * mocks, the same clock, the same connection pool.
 */
@SpringBootTest
@AutoConfigureMockMvc
@RecordApplicationEvents
@Import(BookingTestConfig.class)
public abstract class BookingScenario {

  @ServiceConnection
  static final PostgreSQLContainer<?> POSTGRES = BookingTestDatabase.INSTANCE;

  protected static final String UPC = "UPC";
  protected static final ZoneId LIMA = ZoneId.of("America/Lima");

  /** A tutor, two students and a subject of their own, so no scenario sees another one's rows. */
  protected final UUID tutor = UUID.randomUUID();

  protected final UUID ana = UUID.randomUUID();
  protected final UUID bruno = UUID.randomUUID();
  protected final UUID subject = UUID.randomUUID();

  @Autowired protected MockMvc mockMvc;
  @Autowired protected HourBlockRepository blocks;
  @Autowired protected MutableClock clock;
  @Autowired protected JdbcTemplate jdbc;
  @Autowired protected ApplicationEvents events;
  @Autowired protected FailingConfirmation failingConfirmation;
  @MockitoBean protected IdentityApi identity;
  @MockitoBean protected SkillsApi skills;

  /** The real wallet, watched: a scenario can pause a charge to stage a race. */
  @MockitoSpyBean protected WalletApi wallet;

  @BeforeEach
  void aTutorFreeTomorrowMorning() throws Exception {
    clock.set(Instant.now().truncatedTo(ChronoUnit.SECONDS));

    when(identity.requireTenant(UPC))
        .thenReturn(new TenantView(UPC, "UPC", LIMA.getId(), new BigDecimal("13.00"), true));
    when(identity.isActive(any())).thenReturn(true);
    when(identity.activeTenantCodes()).thenReturn(List.of(UPC));
    when(skills.enabledSkillsOf(tutor)).thenReturn(List.of(subject));
    when(skills.isTutorEnabledFor(tutor, subject)).thenReturn(true);
    when(skills.requireItem(subject))
        .thenReturn(new CatalogItemView(subject, CatalogScope.UNIVERSITY, "Databases I", "1ASI0616"));

    String weekday = today().plusDays(1).getDayOfWeek().name();
    mockMvc
        .perform(
            post("/api/v1/tutor/availability")
                .header("X-Tenant-Id", UPC)
                .header("X-User-Id", tutor)
                .contentType(MediaType.APPLICATION_JSON)
                .content(
                    """
                    {"dayOfWeek":"%s","startsAtTime":"09:00:00","endsAtTime":"12:00:00",
                     "validFrom":"%s"}
                    """
                        .formatted(weekday, today())))
        .andExpect(status().isCreated());
  }

  protected LocalDate today() {
    return LocalDate.now(clock.withZone(LIMA));
  }

  /** Tomorrow at that hour, Lima time, as the instant the API speaks in. */
  protected Instant tomorrowAt(int hour) {
    return ZonedDateTime.of(today().plusDays(1), LocalTime.of(hour, 0), LIMA).toInstant();
  }

  protected HourBlock blockAt(Instant start) {
    return blocks.findWithin(UPC, tutor, start, start.plus(Duration.ofHours(1))).getFirst();
  }

  protected ResultActions hold(UUID student, Instant start, int hours) throws Exception {
    return hold(UPC, student, start, hours);
  }

  protected ResultActions hold(String tenant, UUID student, Instant start, int hours)
      throws Exception {
    return mockMvc.perform(
        post("/api/v1/bookings/holds")
            .header("X-Tenant-Id", tenant)
            .header("X-User-Id", student)
            .contentType(MediaType.APPLICATION_JSON)
            .content(
                """
                {"tutorId":"%s","start":"%s","hours":%d}
                """
                    .formatted(tutor, start, hours)));
  }

  protected ResultActions book(UUID student, Instant start, int hours, String need)
      throws Exception {
    return mockMvc.perform(
        post("/api/v1/bookings")
            .header("X-Tenant-Id", UPC)
            .header("X-User-Id", student)
            .contentType(MediaType.APPLICATION_JSON)
            .content(
                """
                {"tutorId":"%s","catalogItemId":"%s","start":"%s","hours":%d,
                 "needDescription":"%s"}
                """
                    .formatted(tutor, subject, start, hours, need)));
  }

  /** Credits that never expire, which is all most scenarios care about. */
  protected void grant(UUID student, int credits) {
    grant(student, credits, CreditType.EARNED, null);
  }

  protected void grant(UUID student, int credits, CreditType type, Instant expiresAt) {
    TenantContext.runAs(
        UPC, () -> wallet.grant(student, Credits.of(credits), type, expiresAt, UUID.randomUUID()));
  }

  protected int balanceOf(UUID student) {
    AtomicInteger balance = new AtomicInteger();
    TenantContext.runAs(
        UPC, () -> balance.set(wallet.balanceOf(student).available().amount()));
    return balance.get();
  }

  /** Ledger entries that charged this student for a booking. The ledger is append only. */
  protected int chargesOf(UUID student) {
    return jdbc.queryForObject(
        """
        select count(*) from wallet.ledger_entries entry
        join wallet.credit_accounts account on account.id = entry.account_id
        where account.tenant_id = ? and account.user_id = ? and entry.reason = 'BOOKING_CHARGE'
        """,
        Integer.class,
        UPC,
        student);
  }

  /** Sessions scheduled for this student, read as rows: sessions is another module. */
  protected int sessionsOf(UUID student) {
    return jdbc.queryForObject(
        "select count(*) from sessions.sessions where tenant_id = ? and student_id = ?",
        Integer.class,
        UPC,
        student);
  }

  protected int bookingsOf(UUID student) {
    return jdbc.queryForObject(
        "select count(*) from booking.bookings where tenant_id = ? and student_id = ?",
        Integer.class,
        UPC,
        student);
  }

  protected ResultActions release(UUID student, Instant start, int hours) throws Exception {
    return mockMvc.perform(
        delete("/api/v1/bookings/holds")
            .header("X-Tenant-Id", UPC)
            .header("X-User-Id", student)
            .param("tutorId", tutor.toString())
            .param("start", start.toString())
            .param("hours", String.valueOf(hours)));
  }
}
